# Uncomment the next line to define a global platform for your project
 platform :ios, '13.5'

target 'WallDota2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WallDota2
  
  target 'WallDota2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WallDota2UITests' do
    # Pods for testing
  end

end
